### ISSUE TITLE
Data Availability re-orgs handling tracking issue

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#1023]
At present, the Sovereign SDK processes only finalized blocks. To enhance response times,  the SDK should be equipped to manage re-organizations of the blockchain structure due to forks in underlying Data Availability(DA) layers.

## Steps

- [x] Update `rollup-interface` with notion of external storage: https://github.com/Sovereign-Labs/sovereign-sdk/pull/1103
- [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1024
- [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1026
    - [x] Add snapshot support to `sov-schema-db` https://github.com/Sovereign-Labs/sovereign-sdk/pull/1112
    - [x] https://github.com/Sovereign-Labs/sovereign-sdk/pull/1177
    - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1027
    - [x] https://github.com/Sovereign-Labs/sovereign-sdk/pull/1197 
 - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1217
 - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1218

## Prerequisites:
  - [x] https://github.com/Sovereign-Labs/sovereign-sdk/pull/978 as it leaks abstraction
 
 
 ## Finalization and Refactoring
   - [x] Bug: Handle state root change in runner in case of re-org
   - [x] ProverStorageManager: wrapper struct for 3 RwLocks so they all written together.
   - [x] ChangeSet from default Stf should be a different type from PreState
   - [ ] Remove explicit Arc<RwLock<Storage>> from Blueprint and Runner and unify it with RpcStorage.
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1249
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/643 as less types will simplify the change
   - [ ] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1185
   - [ ] Refactor `SchemaIterator` so it utilizes already tested logic of `RawDbIter`
   - [ ] Explore removing Mutex<ChangeSet> inside CacheDb and change API to have &mut self
   - [ ] Optimize CacheDb for multithreaded execution.
