### ISSUE TITLE
Tracking Issue: Fix Endianness in StateDB

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#1174]
- [ ] Find a solution to prevent little-endianness from leaking into versions - possibly by disallowing borsh as a KeyCodec
- [ ] Fix the ordering of the JmtValues table
- [ ] Switch back to a released version of the jmt once the necessary updates land
- [ ] Add tests to ensure that the StateDb is ordered as expected
