### ISSUE TITLE
Tracking Issue: Soft-confirmations

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#1252]
This issue details the items that still need to be completed as part of the soft-confirmations workstream.

 The following list of action items is taken from #1251:
- [x] Completely re-write the integration tests for chain-state (module-system/module-implementations/integration-tests/src/chain_state/tests.rs and module-system/module-implementations/sov-chain-state/tests/all_tests.rs)
 - [x] Completely re-write the integration tests for blob-selection
 - [x] Remove DA-related information from the normal SlotHooks
 - [x] Implement kernel logic to manage the user-space view of DA layer information
 - [ ] Simplify initialization logic for kernel and runtime
 - [ ] Re-enable chain-state RPC
 - [ ] Document Kernel and it's responsibilities
 - [ ] Document the method for soft-confirmations
 - [x] Add `trybuild` tests to enforce that `#[derive(ModuleInfo)]` makes the appropriate check that the deriving type is a `Module`
 - [ ] Tests for recovery mode
 - [ ] Implement blob selection for MockKernel https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/48
 - [ ] Implement sequencer for soft-confirmations
