### ISSUE TITLE
Tracking issue: Reduce the number of cycles for the zk prover.

### ISSUE THREAD

**Issue by theochap** [Sovereign-Labs/sovereign-sdk#1271]
**Description**
This is a tracking issue to bring down the number of cycles from the zk-prover's main process (ie all the operations outside of signature computation).

**Potential areas of improvement**

- [x] Include sha2, ed25519 and crypto-bigint patches #1245, #1278
- [ ] Reduce the number of hash computation for the jmt by grouping updates in batches #451
- [ ] Implement zero-copy serialization/deserialization for borsh #433
- [ ] Increase the size of the jmt leaves #629

Current stats for the demo-prover:
* Standard hash function patched with risc0/rust_crypto
* Signature verification patched

Block stats
| Description                           | Value |
|---------------------------------------|-------|
| Total blocks                          | 3     |
| Blocks with transactions              | 3     |
| Number of blobs                       | 3     |
| Total number of transactions          | 14    |
| Average number of transactions per block | 1   |

Cycle Metrics

| Function               | Average Cycles | Num Calls |
|------------------------|----------------|-----------|
| Cycles per block       | 5122643        | 3         |
| apply_blob             | 3932560        | 3         |
| verify                 | 749219         | 4         |
| end_slot               | 648684         | 3         |
| compute_state_update   | 610264         | 3         |
| begin_slot             | 91216          | 3         |

**Comment by citizen-stig** [comment]
I thought that signature verification was patched in scope of https://github.com/Sovereign-Labs/sovereign-sdk/pull/1245

**Comment by theochap** [comment]
> I thought that signature verification was patched in scope of #1245

@preston-evans98 ?
