### ISSUE TITLE
Tracking Issue: Prepare SDK Internals for Testnet

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#1272]
This issue is a list of all known issues in the SDK internals that need to be resolved before testnet. This list is currently a WIP: Maintainers, free to add issues as appropriate.

 - [ ] Gas https://github.com/Sovereign-Labs/sovereign-sdk/issues/655 (@vlopes11)
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1285
   - [ ] Reward sequencers
   - [x] Reward Provers (zk-only) https://github.com/Sovereign-Labs/sovereign-sdk/issues/271
 - [ ] Proving (cc @bkolad)
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/494  
 - [ ] Sequencer Improvements (@neysofu)
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/391
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/466
   - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1090
   - [ ] https://github.com/Sovereign-Labs/sovereign-sdk/issues/949
   - [ ] https://github.com/Sovereign-Labs/sovereign-sdk/issues/435
   - [ ] Race condition when locking `Mutex<B>` with `B: BatchBuilder`.
   - [x] Sequencer should be runtime aware (corrrect account pullL (mentioned in https://github.com/Sovereign-Labs/sovereign-sdk/issues/434) @citizen-stig 
 - [ ] Soft-confirmations (@preston-evans98)
   - [ ] #1252 
   - [ ] https://github.com/Sovereign-Labs/sovereign-sdk/issues/408
 - [ ] #1314
   - [ ] Replace user-defined event keys with autogenerated ones & improve event usability (https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/71)
 - [x] Fork Management (@citizen-stig)
    - [x] https://github.com/Sovereign-Labs/sovereign-sdk/issues/1023
 - [ ] Optimistic Incentive Management (@theochap)
 - [ ] Make EVM zk-provable (@citizen-stig)
 - [x] Archival State (@dubbelosix)
 - [ ] Block Explorer (?)
 - [ ] Metamask Snap (?)
   - [ ] https://github.com/Sovereign-Labs/sovereign-sdk/issues/982
 - [ ] Hardware Wallet (Not needed for first testnet)
 - [ ] Testnet Devops 
 - [ ] Testing Harness (run 1000s of txs acrosss many blocks with forks/reorgs etc.)
