### ISSUE TITLE
Implement EIP-1559 style fee gas-price adjustment

### ISSUE THREAD

**Issue by vlopes11** [Sovereign-Labs/sovereign-sdk#1285]
With EIP-1559, setting a fixed gas target is feasible due to the relatively consistent behavior of the Ethereum Virtual Machine (EVM) and its execution environment, attributed to the deterministic nature of opcodes and storage access. However, for zk-Rollups, there is increased volatility. Not only do we encounter multiple dimensions for gas pricing (comprising native and ZK fees), but the costs associated with ZK verification are anticipated to undergo significant fluctuations in the near future, driven by expected advancements in both hardware and software. To accommodate this instability, it is essential to provide users with the flexibility to adopt a more adaptive gas target strategy.

The calculation of the base price for the current block execution determines the slope of the parents' gas target and gas consumption. This value is then multiplied by the parents' price and divided by the maximum elasticity factor.

```
gas target := chain[height - GAS_PRICE_BLOCKS_DEPTH..height].gas used.sum() / GAS_PRICE_BLOCKS_DEPTH
gas price := chain[height - 1].gas price - chain[height - 1].gas price ⋅ ( gas target - chain[height - 1].gas used ) / gas target / GAS_PRICE_MAXIMUM_ELASTICITY
```

TODO:

- [ ] unlock a query with the height parameter, delivering block data such as transaction receipts and committed gas price.
- [ ] introduce an optional `maximum gas price` field to the transaction. If the actual gas price exceeds this limit, the transaction owner will be charged only the base cost. This field will have indeterminate dimensions, which will be adjusted to align with the current gas price's dimension in the given context.
- [ ] add `GAS_PRICE_BLOCKS_DEPTH` and `GAS_PRICE_MAXIMUM_ELASTICITY` constants.
- [ ] commit `gas target` and `gas price` to the chain state of the block.
- [ ] create a blob hook for the sequencer registry module to handle extraordinary costs, specifically those where the account owner lacked sufficient funds to cover the transaction base costs.
- [ ] create a framework to measure and assign gas costs crypto primitives such as hashing and signature verification functions.
- [ ] create an Oracle API to calculate the gas cost for a transaction, taking into account current gas prices, as well as the utilized modules and primitives.

**Comment by theochap** [comment]
This issue is outdated. Hence,  I am closing it
