### ISSUE TITLE
Tracking Issue: Improve CI

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#188]
## Comprehensiveness
- [x] Add coverage (see https://lib.rs/crates/cargo-tarpaulin)
- [x] Consider adding license check (cc @citizen-stig) https://github.com/Sovereign-Labs/sovereign-sdk/pull/559
- [x] Consider adding clippy
- [x] Check docstrings
- [x] Introduce job dependencies. Run `check` first, and other jobs run only if it succeeds. So if PR is completely broken, not a lot of resources will be wasted. 

## Performance
CI runtime has gone from 30 minutes to 10 minutes. (Thanks @citizen-stig for switching to `sccache`in #197). We would like to reduce this time even further.

## Some Ideas (TODO: expand, evaluate tradeoffs)
- Separate sov-state into two crates: one which provides the API and one which provides the implementation. This would let us avoid depending on RocksDB everywhere. 
- Move the sov-modules-macros tests into their own crate instead of relying on `trybuild` so that they can build in parallel with other items instead of sequentially.

Thanks @bkolad for the suggestion

**Comment by preston-evans98** [comment]
@citizen-stig Suggests that `sccache` might alleviate the compilation bottleneck.

**Comment by citizen-stig** [comment]
Checked running time of the tests and we are fine, except for 2 tests, which are big offenders:

<img width="478" alt="Screenshot 2023-04-24 at 20 29 54" src="https://user-images.githubusercontent.com/3115300/234084729-c80f2d4e-3d7f-4b25-8da0-6a5c079ad1c9.png">

But still they should not lead to 20-30 minutes time of the CI

**Comment by citizen-stig** [comment]
Some tips recommended by @bkolad :

https://www.youtube.com/watch?v=xUH-4y92jPg

**Comment by citizen-stig** [comment]
Also there were some comments in #439 in description

**Comment by citizen-stig** [comment]
@neysofu you might be interested in this one.

**Comment by neysofu** [comment]
I would propose we close this –it's outdated at this point– and create single issues for more specific improvements we want to make.

**Comment by preston-evans98** [comment]
Agreed. Closing.
