### ISSUE TITLE
Tracking Issue: `sov-cli` improvements

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#552]
## Background
`sov-cli` grew organically from a simple transaction generator for the bank module into a complex command line tool. Unfortunately, this organic growth has made it more and more unwieldy over time. At Modular summit, one of the biggest pieces of feedback we received was that the cli was unintuitive and hard to use. This is completely fair. Now that #423, #525, and #446  have landed, we have the scaffolding to re-architect the CLI into a standalone crate and provide a much better UX. 

## Tasks
- [x] Move sov-cli into its own crate
- [ ] Refactor `sov-cli` interface to make it easier to use
- [x] Add persistance (i.e. for private keys) to `sov-cli`
- [x] Add RPC capabilities to `sov-cli`
